<?php

    if( function_exists('acf_add_options_page') ) {

        acf_add_options_page( [
                'page_title' 	=> 'Nastavenia stránky',
                'menu_title'	=> 'Nastavenia stránky',
                'menu_slug' 	=> 'theme-general-settings',
                'capability'	=> 'edit_posts',
                'redirect'		=> false
            ] );
    }

    /* Settings */
    if( function_exists('acf_add_local_field_group') ):

        acf_add_local_field_group(array(
                                      'key' => 'group_5e98da3b5de15',
                                      'title' => 'Nastavenia',
                                      'fields' => array(
                                          array(
                                              'key' => 'field_5e98da42f9297',
                                              'label' => 'Verzia',
                                              'name' => '',
                                              'type' => 'tab',
                                              'instructions' => '',
                                              'required' => 0,
                                              'conditional_logic' => 0,
                                              'wrapper' => array(
                                                  'width' => '',
                                                  'class' => '',
                                                  'id' => '',
                                              ),
                                              'placement' => 'top',
                                              'endpoint' => 0,
                                          ),
                                          array(
                                              'key' => 'field_5e98da5df9298',
                                              'label' => 'Zapnúť zobrazovanie verzie',
                                              'name' => 'version_display',
                                              'type' => 'true_false',
                                              'instructions' => '',
                                              'required' => 0,
                                              'conditional_logic' => 0,
                                              'wrapper' => array(
                                                  'width' => '33',
                                                  'class' => '',
                                                  'id' => '',
                                              ),
                                              'message' => '',
                                              'default_value' => 1,
                                              'ui' => 1,
                                              'ui_on_text' => 'Zobraziť',
                                              'ui_off_text' => 'Schovať',
                                          ),
                                          array(
                                              'key' => 'field_5e98daa0f9299',
                                              'label' => 'Fáza verzie',
                                              'name' => 'version_phase',
                                              'type' => 'text',
                                              'instructions' => '',
                                              'required' => 0,
                                              'conditional_logic' => 0,
                                              'wrapper' => array(
                                                  'width' => '33',
                                                  'class' => '',
                                                  'id' => '',
                                              ),
                                              'default_value' => '',
                                              'placeholder' => '',
                                              'prepend' => '',
                                              'append' => '',
                                              'maxlength' => '',
                                          ),
                                          array(
                                              'key' => 'field_5e98db0ef929a',
                                              'label' => 'Info text verzie',
                                              'name' => 'version_info',
                                              'type' => 'text',
                                              'instructions' => 'Je možné pridať link do textu. Dátum sa zobrazí automaticky, podľa aktuálne poslednej úpravy ktorejkoľvek stránky.',
                                              'required' => 0,
                                              'conditional_logic' => 0,
                                              'wrapper' => array(
                                                  'width' => '',
                                                  'class' => '',
                                                  'id' => '',
                                              ),
                                              'default_value' => 'Toto je pracovná verzia, pracujeme na jej zdokonaľovaní. Naposledy aktualizované:',
                                              'placeholder' => '',
                                              'prepend' => '',
                                              'append' => '',
                                              'maxlength' => '',
                                          ),
                                          array(
                                              'key' => 'field_5e99cf3c82074',
                                              'label' => 'Dátum poslednej aktualizácie',
                                              'name' => 'version_date',
                                              'type' => 'text',
                                              'instructions' => '',
                                              'required' => 0,
                                              'conditional_logic' => 0,
                                              'wrapper' => array(
                                                  'width' => '',
                                                  'class' => '',
                                                  'id' => '',
                                              ),
                                              'default_value' => '',
                                              'placeholder' => '',
                                              'prepend' => '',
                                              'append' => '',
                                              'maxlength' => '',
                                          ),
                                          array(
                                              'key' => 'field_5ea75d13981c2',
                                              'label' => 'Aktuálne opatrenia/zmeny',
                                              'name' => '',
                                              'type' => 'tab',
                                              'instructions' => '',
                                              'required' => 0,
                                              'conditional_logic' => 0,
                                              'wrapper' => array(
                                                  'width' => '',
                                                  'class' => '',
                                                  'id' => '',
                                              ),
                                              'placement' => 'top',
                                              'endpoint' => 0,
                                          ),
                                          array(
                                              'key' => 'field_5ea75dde981c4',
                                              'label' => 'Zobrazenie',
                                              'name' => 'opatrenia',
                                              'type' => 'true_false',
                                              'instructions' => '',
                                              'required' => 0,
                                              'conditional_logic' => 0,
                                              'wrapper' => array(
                                                  'width' => '50',
                                                  'class' => '',
                                                  'id' => '',
                                              ),
                                              'message' => '',
                                              'default_value' => 0,
                                              'ui' => 1,
                                              'ui_on_text' => 'Zobraziť',
                                              'ui_off_text' => 'Schovať',
                                          ),
                                          array(
                                              'key' => 'field_5ea75e07981c5',
                                              'label' => 'Farba pozadia',
                                              'name' => 'farba_opatrenia',
                                              'type' => 'radio',
                                              'instructions' => '',
                                              'required' => 0,
                                              'conditional_logic' => 0,
                                              'wrapper' => array(
                                                  'width' => '50',
                                                  'class' => '',
                                                  'id' => '',
                                              ),
                                              'choices' => array(
                                                  'red' => '<div style="display:inline-block; background-color: #df3034; width: 16px; height: 16px;"></div> Červené',
                                                  'yellow' => '<div style="display:inline-block; background-color: #ffbf47; width: 16px; height: 16px;"></div> Žlté',
                                                  'lgray' => '<div style="display:inline-block; background-color: #f1f1f1; width: 16px; height: 16px;"></div> Šedé',
                                              ),
                                              'allow_null' => 0,
                                              'other_choice' => 0,
                                              'default_value' => 'yellow',
                                              'layout' => 'horizontal',
                                              'return_format' => 'value',
                                              'save_other_choice' => 0,
                                          ),
                                          array(
                                              'key' => 'field_5ea75d40981c3',
                                              'label' => 'Text opatrení',
                                              'name' => 'text_opatreni',
                                              'type' => 'textarea',
                                              'instructions' => 'Povolené značky: <code style="-webkit-user-select: all; -moz-user-select: all; -ms-user-select: all; user-select: all;">&lt;strong&gt;</code> a <code style="-webkit-user-select: all; -moz-user-select: all; -ms-user-select: all; user-select: all;">&lt;/strong&gt;</code>',
                                              'required' => 0,
                                              'conditional_logic' => 0,
                                              'wrapper' => array(
                                                  'width' => '',
                                                  'class' => '',
                                                  'id' => '',
                                              ),
                                              'default_value' => '',
                                              'placeholder' => '',
                                              'maxlength' => '',
                                              'rows' => 3,
                                              'new_lines' => '',
                                          ),
                                          array(
                                              'key' => 'field_5ec69e67a0f83',
                                              'label' => 'Interný/externý link',
                                              'name' => 'link_type',
                                              'type' => 'true_false',
                                              'instructions' => '',
                                              'required' => 0,
                                              'conditional_logic' => 0,
                                              'wrapper' => array(
                                                  'width' => '',
                                                  'class' => '',
                                                  'id' => '',
                                              ),
                                              'message' => '',
                                              'default_value' => 1,
                                              'ui' => 1,
                                              'ui_on_text' => 'Interný',
                                              'ui_off_text' => 'Externý',
                                          ),
                                          array(
                                              'key' => 'field_5ea75f61981c6',
                                              'label' => 'Link na všetky opatreia',
                                              'name' => 'link_opatrenia',
                                              'type' => 'post_object',
                                              'instructions' => '',
                                              'required' => 0,
                                              'conditional_logic' => array(
                                                  array(
                                                      array(
                                                          'field' => 'field_5ec69e67a0f83',
                                                          'operator' => '==',
                                                          'value' => '1',
                                                      ),
                                                  ),
                                              ),
                                              'wrapper' => array(
                                                  'width' => '50',
                                                  'class' => '',
                                                  'id' => '',
                                              ),
                                              'post_type' => array(
                                                  0 => 'page',
                                              ),
                                              'taxonomy' => '',
                                              'allow_null' => 0,
                                              'multiple' => 0,
                                              'return_format' => 'id',
                                              'ui' => 1,
                                          ),
                                          array(
                                              'key' => 'field_5ec69ec3a0f84',
                                              'label' => 'Externý link',
                                              'name' => 'externy_link',
                                              'type' => 'text',
                                              'instructions' => '',
                                              'required' => 0,
                                              'conditional_logic' => array(
                                                  array(
                                                      array(
                                                          'field' => 'field_5ec69e67a0f83',
                                                          'operator' => '!=',
                                                          'value' => '1',
                                                      ),
                                                  ),
                                              ),
                                              'wrapper' => array(
                                                  'width' => '40',
                                                  'class' => '',
                                                  'id' => '',
                                              ),
                                              'default_value' => '',
                                              'placeholder' => '',
                                              'prepend' => '',
                                              'append' => '',
                                              'maxlength' => '',
                                          ),
                                          array(
                                              'key' => 'field_5ea75fa8981c7',
                                              'label' => 'Text pre link',
                                              'name' => 'link_opatrenia_text',
                                              'type' => 'text',
                                              'instructions' => '',
                                              'required' => 0,
                                              'conditional_logic' => 0,
                                              'wrapper' => array(
                                                  'width' => '50',
                                                  'class' => '',
                                                  'id' => '',
                                              ),
                                              'default_value' => '',
                                              'placeholder' => '',
                                              'prepend' => '',
                                              'append' => '',
                                              'maxlength' => '',
                                          ),
                                          array(
                                              'key' => 'field_5ec69f2ba0f85',
                                              'label' => 'New tab',
                                              'name' => 'new_tab',
                                              'type' => 'checkbox',
                                              'instructions' => '',
                                              'required' => 0,
                                              'conditional_logic' => array(
                                                  array(
                                                      array(
                                                          'field' => 'field_5ec69e67a0f83',
                                                          'operator' => '!=',
                                                          'value' => '1',
                                                      ),
                                                  ),
                                              ),
                                              'wrapper' => array(
                                                  'width' => '10',
                                                  'class' => '',
                                                  'id' => '',
                                              ),
                                              'choices' => array(
                                                  '_blank' => 'Nové okno',
                                              ),
                                              'allow_custom' => 0,
                                              'default_value' => array(
                                              ),
                                              'layout' => 'vertical',
                                              'toggle' => 0,
                                              'return_format' => 'value',
                                              'save_custom' => 0,
                                          ),
                                      ),
                                      'location' => array(
                                          array(
                                              array(
                                                  'param' => 'options_page',
                                                  'operator' => '==',
                                                  'value' => 'theme-general-settings',
                                              ),
                                          ),
                                      ),
                                      'menu_order' => 0,
                                      'position' => 'normal',
                                      'style' => 'default',
                                      'label_placement' => 'top',
                                      'instruction_placement' => 'label',
                                      'hide_on_screen' => '',
                                      'active' => true,
                                      'description' => '',
                                  ));

    endif;
